### ISSUE TITLE
Steve Skin Problem 

### ISSUE THREAD

**Issue by DragonfireHD** [TungstenVn/Clothes#10]
When I Chose a Wing from /clo the Skin changed to the Steve skin the wing is on it but i dont need the Steve skin i need my own Skin

And how can i add more Wings Skins? can you me help for this? i dont now how can I change a png in json geometry on a Mobile

**Comment by TungstenVn** [comment]
You must already have the skin on before joining the server, than use can use any wing on /clo with your custom skin

And i also wrote a info for how to create more clothes, see them in the poggit page:
https://poggit.pmmp.io/p/Clothes/3.1.0

**Comment by TungstenVn** [comment]
https://poggit.pmmp.io/p/Clothes/
