### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ZStarMCZ5487** [TungstenVn/Clothes#18]
why its not work when i change the model inside the plugin?

**Comment by ZStarMCZ5487** [comment]
someone plz help me 😢

**Comment by TungstenVn** [comment]
can you provide me more info about ur case?

**Comment by ZStarMCZ5487** [comment]
i put the model in cosplay file and renamed it to long_neck.json , and put the texture and renamed t , but the texture not load

**Comment by TungstenVn** [comment]
did you change the name inside the json file

**Comment by ZStarMCZ5487** [comment]
i have

**Comment by ZStarMCZ5487** [comment]
i change it to geometry.cosplays/dinosaur

**Comment by TungstenVn** [comment]
so the file name should be dinosaur.json not long_neck.json

**Comment by ZStarMCZ5487** [comment]
how to make a clothes shop with EconomyAPI?

**Comment by TungstenVn** [comment]
you can simply create a new plugin for player buying permission,etc

**Comment by ZStarMCZ5487** [comment]
ohh , thanks (but idk how to code shop 🤣😂🤣😂)

**Comment by ZStarMCZ5487** [comment]
oh the skin work now :)
