### ISSUE TITLE
player's skin gets cut in pieces

### ISSUE THREAD

**Issue by mote166** [TungstenVn/Clothes#3]
![Screenshot_20200312_011421_net zhuoweizhang mcpelauncher](https://user-images.githubusercontent.com/19583571/76470702-d8025d80-6401-11ea-8644-829ed043bc29.jpg)
after i reset it with the plugin
![Screenshot_20200312_011444_net zhuoweizhang mcpelauncher](https://user-images.githubusercontent.com/19583571/76470714-dd5fa800-6401-11ea-9713-f4bbe66f2f6e.jpg)

after i rejoin
![Screenshot_20200312_011546_net zhuoweizhang mcpelauncher](https://user-images.githubusercontent.com/19583571/76470736-eb152d80-6401-11ea-81d3-929100c6cf8d.jpg)

**Comment by TungstenVn** [comment]
lul so weird

**Comment by TungstenVn** [comment]
maybe because of your skin png size, is it 64x64 or what

**Comment by TungstenVn** [comment]
can you try again with the new one i just uploaded

**Comment by mote166** [comment]
my skin is slim, idk how to know.

and the issue is still there

**Comment by mote166** [comment]
it works fine when the skin is normal but when its slim it gets cut

**Comment by TungstenVn** [comment]
cool

**Comment by mote166** [comment]
its not cool, almost all of the players use slim skins

**Comment by TungstenVn** [comment]
This error is fixed in new version (2.1.0) let wait until it release on poggit

**Comment by thebigsmileXD** [comment]
> https://github.com/TungstenVn/Clothes/blob/5bc4a558bbd9eafe7a09cc2211ee3cad1ecab6d6/src/TungstenVn/Clothes/skinStuff/resetSkin.php#L23-L28
You could use getimagesize to support any skin size :P

`$s` currently is height (index 1)
Suggestion:
```php
        [$width, $height] = getimagesize($path);
        for($y = 0; $y < $height; $y++) { 
             for($x = 0; $x < $width; $x++) { 
```

Same issue seems to exist in multiple places

**Comment by TungstenVn** [comment]
this plugin is now working very well for player who has 64x64 and 128x128 skin size
seem like the code get lucky 'cuz $s and $size in those code is equal (64x64 and 128x128),isnt it

i would need to fix that if i make the plugin works for 64x32 skin size but i had one more bigger problem than the one above

https://github.com/TungstenVn/Clothes/blob/5bc4a558bbd9eafe7a09cc2211ee3cad1ecab6d6/src/TungstenVn/Clothes/skinStuff/saveSkin.php#L32-L33

this code only works well for converting hex to img of a 64x64 and 128x128 size, 64x32 doesnt work well and im very sure i dont know what that code does

**Comment by thebigsmileXD** [comment]
This might be better code:
https://github.com/HimbeersaftLP/LibSkin/blob/master/LibSkin/src/Himbeer/LibSkin/SkinConverter.php#L15-L43

Oh, i see only now that you use the skinapi code. Why not use the virion directly?
Remember that skinapi is licensed under GPL3 (i don't really care tbh :P)

**Comment by mote166** [comment]
after u finish this convo feel free to close this issue since i only use 128x128 and 64x64 skins only and its fixed for me.
