### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Johnsonk79** [TungstenVn/Clothes#7]
Awesome plugin, but please remove or make it so that the player can choose if they want the
`Player is using a 4D skin`
Message to appear every time a player joins the server, it spams the chat and is kinda annoying. Thanks!

**Comment by TungstenVn** [comment]
okay this feature will be included in the next release

**Comment by Johnsonk79** [comment]
thx!

**Comment by TungstenVn** [comment]
the announcement ``Player is using a 4D skin`` is removed and no longer need in new version 4.1.0

**Comment by TungstenVn** [comment]
https://poggit.pmmp.io/p/Clothes/
